### ISSUE TITLE
Error on npm install command

### ISSUE THREAD

**Issue by abhimanusharma** [dangrie158/TelnetDemoServer#1]
Hi,

As there is no description given in README of this repo, understanding of system and software required to run this code is unclear.
I downloaded the master of this code and after extracted the zip, run the command npm install in the code directory.
I am getting below error.

```
> pty.js@0.3.1 install C:\xampp\htdocs\laravel\wipro\exercise2\TelnetDemo\node_modules\pty.js
> node-gyp rebuild


C:\xampp\htdocs\laravel\wipro\exercise2\TelnetDemo\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\Abhi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Abhi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\ProgramData\Miniconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Abhi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\laravel\wipro\exercise2\TelnetDemo\node_modules\pty.js
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abhi\AppData\Roaming\npm-cache\_logs\2020-07-09T06_35_04_294Z-debug.log

```

**Comment by dangrie158** [comment]
Hi,

this is not an issue with this project but with one of it's dependencies which is no longer supported. (pty.js).
You could try to pull one of the forks of this dependency from the pull requests which tries to fix the issue (e.g. https://github.com/chjj/pty.js/pull/199)
